### ISSUE TITLE
Unable to recognize related hashtags when a comma (or maybe other symbols) appears after them

### ISSUE THREAD

**Issue by kokabi1365** [amirhoseinsalimi/programmer-fa#11]
For example, the bot can not recognize the following tweet, because  a comma has been used after "برنامه‌نویسی#", 
"... یکی از مشکلات #برنامه‌نویسی، گستردگی بیش از حد"

**Comment by amirhoseinsalimi** [comment]
Thanks for your report, please send the tweet URL for further checks (And I will also retweet it by hand).

**Comment by kokabi1365** [comment]
https://twitter.com/kokabi1365/status/1325746344821219329?s=20

**Comment by kokabi1365** [comment]
https://twitter.com/kokabi1365/status/1325746344821219329

**Comment by amirhoseinsalimi** [comment]
Just tested the exact text again and got a retweet!
I resolved many minor issues regarding logic last week and it seems this specific issue is gone too.


![Screenshot from 2020-12-27 18-56-58](https://user-images.githubusercontent.com/25503371/103174275-fc86d380-4875-11eb-993f-5d8daccc21c2.png)
![Screenshot from 2020-12-27 18-56-53](https://user-images.githubusercontent.com/25503371/103174276-ff81c400-4875-11eb-989b-f09e857de809.png)
