### ISSUE TITLE
Sometimes (usually at night ), the bot doesn't work

### ISSUE THREAD

**Issue by kokabi1365** [amirhoseinsalimi/programmer-fa#12]
I don't know exactly when or under what circumstances, but sometimes usually at night, the bot doesn't work at all (neither retweet nor like)!

**Comment by amirhoseinsalimi** [comment]
Hey!
That's what I'm also very curious about! I have to review logs on the server to see why this happens. I think the bot misses tweets. It may be caused by:

- Broken connection
- Process Manager (pm2) fault
- Twitter stream doesn't send all tweets to my client

**Comment by kokabi1365** [comment]
I just noticed something weird that may be related to this bug. Twitter didn't suggest me hashtag "برنامه_نویسی" when I was writing a tweet.
