### ISSUE TITLE
طرفداران بند های موسیقی کره ای

### ISSUE THREAD

**Issue by aliraza7926** [amirhoseinsalimi/programmer-fa#23]
بعضی از طرفدار های گروه های موسیقی مثل exo و bts با زدن هشتگ برنامه نویسی و کلی هشتگ دیگه راجع به گروه موسیقی مورد علاقشون تلاش میکنن ویو بیشتری برای خودشون بگیرن اگه میشه هشتگ های اصلی این گروه ها رو توی بلاک لیست قرار بدین

**Comment by amirhoseinsalimi** [comment]
سلام متشکرم که اطلاع دادی
همین الان میذارم

**Comment by amirhoseinsalimi** [comment]
لطفا اگر باز هم به چشمت خورد اطلاع بده تا هم اکانت هاشون رو بذارم توی بلاک لیست و هم کلماتشون رو
