### ISSUE TITLE
Configure lintstaged

### ISSUE THREAD

**Issue by amirhoseinsalimi** [amirhoseinsalimi/programmer-fa#87]

**Comment by hosamsayahi** [comment]
@amirhoseinsalimi can I work on this one?

**Comment by amirhoseinsalimi** [comment]
@HosamIntel Sure. You can also use [this repo of mine](https://github.com/amirhoseinsalimi/exdevs-ir) to get some idea. I will really appreciate it. Please make sure to fork from `v2` and send a PR to `v2`.

**Comment by amirhoseinsalimi** [comment]
Solved by #88
